name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploying to surge

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run build:css
      - run: npm install -g surge
      - run: surge ./ ${{ secrets.SURGE_DEV_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
