name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploying to Firebase

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 18
      - run: npm run build:css
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_GIMHANA }}"
          channelId: live
          projectId: portfolio-gimhana
